version: '3.8'
services:
    database:
        container_name: blog_db
        image: mongo
        env_file: .env
        environment:
            - MONGO_INITDB_ROOT_USERNAME = $MONGO_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD = $MONGO_PASSWORD
        ports:
            - 127.0.0.1:27017:27017
        volumes:
            - mongo_data:/data/db
            - mongo_data_config:/data/configdb
    web:
        container_name: blog_web
        build:
            context: .
            dockerfile: Dockerfile
        image: nodejs
        env_file: .env
        environment:
            - MONGO_USERNAME=$MONGO_USERNAME
            - MONGO_PASSWORD=$MONGO_PASSWORD
            - MONGO_HOSTNAME=$MONGO_HOSTNAME
            - MONGO_PORT=$MONGO_PORT
            - MONGO_DB=$MONGO_DB
        depends_on:
            - database
        ports:
            - 127.0.0.1:80:3000
        volumes:
            - ./src:/home/node
        command: npm run dev
volumes:
    mongo_data:
    mongo_data_config:

