version: '3.8'
services:
    db:
        container_name: blog-db
        image: mongo
        ports:
            - 127.0.0.1:27017:27017
        volumes:
            - mongo_data:/data/db
            - mongo_data_config:/data/configdb
    server:
        container_name: blog-server
        build:
            context: .
            dockerfile: Dockerfile
        env_file: .env
        depends_on:
            - db
        ports:
            - 127.0.0.1:$BACKEND_PORT:$BACKEND_PORT
        volumes:
            - .:/home/node
        command: npm run dev
    client:
        container_name: blog-client
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
            - server
        ports:
            - 127.0.0.1:3000:3000
        volumes:
            - ./client:/home/node
        command: npm run start 
volumes:
    mongo_data:
    mongo_data_config:

