version: '3.8'
services:
    db:
        container_name: blog-db
        image: mongo
        ports:
            - 127.0.0.1:27017:27017
        volumes:
            - mongo_data:/data/db
            - mongo_data_config:/data/configdb
    backend:
        container_name: blog-backend
        build:
            context: .
            dockerfile: Dockerfile
        env_file: .env
        depends_on:
            - db
        ports:
            - 127.0.0.1:$BACKEND_PORT:$BACKEND_PORT
        volumes:
            - ./src/backend:/home/node
        command: npm run dev
    frontend:
        container_name: blog-frontend
        build:
            context: .
            dockerfile: Dockerfile
        env_file: .env
        depends_on:
            - backend
        ports:
            - 127.0.0.1:$FRONTEND_PORT:3000
        volumes:
            - ./src/frontend:/home/node
        command: npm start
volumes:
    mongo_data:
    mongo_data_config:

